### ISSUE TITLE
url rewrite fails on xampp machines (Windows)

### ISSUE THREAD

**Issue by senneschall** [OpenRA/OpenRAMasterServer#34]
RewriteRules in .htaccess don't work on xampp machines. Tested with xampp 1.7.7 and xampp 1.8.2 on Win7 and WinXP.

An overall redirection does the trick there:

---
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^([^\.]+)?$ $1.php

---

**Comment by ihptru** [comment]
Thanks, updated.
