### ISSUE TITLE
Dedicated Server listing not sorted alphanumerically

### ISSUE THREAD

**Issue by oraservers** [OpenRA/OpenRAMasterServer#46]
Recently, it appears that the server listings are sorted in some manner other than alphabetical. In the past, server names have determined the order in which servers without any players appear in the server listing, and similarly among the group of servers that have current active players.

It is not clear how they are now being sorted or if this change in sorting mechanism was intentional.

**Comment by pchote** [comment]
Regression from #44.  Now fixed.
