### ISSUE TITLE
security, ping.php, address 

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRAMasterServer#58]
port check is done on $_SERVER["REMOTE_ADDR"] yet address in body is used in the database insert/update clause. perhaps you want to add a check that remote address matches body address and/or store remote address.

by setting the ip address to any active game ip address you can update/overwrite the database record for that game server.

in general many of the input fields are not checked, but the address being part of the key may be harmful.

also note that a dos attack is possible by executing an unlimited number of pings. i understand this may be by design, it being an open game.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRAMasterServer/blob/95f17e30e950467db579abb495888bc94c0bda90/ping.php#L455

is the line which defines the value for `address`, which uses the port defined by the user and (should) ignores any user-defined IP.  Can you please clarify whether you have an active testcase that allows this to be bypassed?

**Comment by anvilvapre** [comment]
i missed that line, misread. also mixed up name and address keys.
